- lib/groonga/query-log/analyzer/reporter/console.rb
- lib/groonga/query-log/command/extract.rb
This commit makes Travis-CI test case green again.
> Use .command_name which is introduced since groonga-command 1.2.3

- lib/groonga/query-log/command/run-regression-test.rb
The value of --skip-finished-queries option must be passed as Tester
option, but actually it is passed as Server option. It doesn't work
correctly.
> Fix a bug that --skip-finished-queries doesn't work

- lib/groonga/query-log/command/run-regression-test.rb
- lib/groonga/query-log/command/verify-server.rb
- lib/groonga/query-log/response-comparer.rb
- lib/groonga/query-log/server-verifier.rb
永続化キャッシュのテスト用にキャッシュヒット率を検証するための機能を追加しました。
追加した機能は以下の通りです。
* `--cache-base-path`オプションが付与されたgroongaを定期的に再起動します。
* 再起動のタイミングは、`query-logs/`配下のlogファイル実行毎に1度行います。
* `query-logs/`配下に6ファイルあれば、6回再起動されます。
* 新旧いずれかのgroongaに`--cache-base-path`オプションが付与された場合に、1クエリー実行毎に1回`status`コマンドを実行します。
* 実行した`status`コマンドの`cache_hit_rate`の値を比較し、異なっている場合は、`status`コマンドの結果を`results/`配下に出力します。
> Add feature that verify cache hit rate. 

- test/test-parser.rb
Since Groonga 7.0.1, the query log format about drilldown is changed.
Before:
drilldown(N)
After:
output.drilldown(N)
> Support changed format about drilldown

- test/test-parser.rb
Using v0, v1 for test name is not suitable, it is better to use more
meaningful name for test case.
> Use more meaningful test name

- lib/groonga/query-log/parser.rb
- test/test-parser.rb
Since Groonga 7.0.1, the query which uses labeled drilldown is
changed. This commit supports parsing drilldown(N)[LABEL] case again.
Before:
drilldown(N)[LABEL]
After:
output.drilldowns[LABEL](N)
> Support changed format about labeled drilldown

- lib/groonga/query-log/parser.rb
For example, empty command is logged in query log,
it raises exception.
> (empty)
TODO: write test case
> Don't create statistic when command is missing

- lib/groonga/query-log/command/detect-memory-leak.rb
Without this change, it causes uninitialized constant error.
detect-memory-leak.rb:45:in `create_parser': uninitialized constant Groonga::QueryLog::Command::DetectMemoryLeak::VERSION (NameError)
from /home/kenhys/work/groonga/groonga-query-log.work/lib/groonga/query-log/command/detect-memory-leak.rb:32:in `run'
> Add missing version

- lib/groonga-query-log/response-comparer.rb
- test/test-response-comparer.rb
Because of the difference in accuracy of float values between before and after Groonga v6.0.4.
> response-comparer: Modify to ignore the difference in accuracy of float values

- lib/groonga-query-log/command/run-regression-test.rb
Because grn_file is undefined.
> run-regression-test: fix a wrong variable name

- lib/groonga-query-log/server-verifier.rb
Improve "stop-on-failure" option so as to stop the execution of tests even when causing HTTP errors.
> run-regression-test: support HTTP error case

- lib/groonga-query-log/command/format-regression-test-logs.rb
- test/command/test-format-regression-test-logs.rb
It makes easy to collect output when invoked from other groonga-query-log command.
> run-regression-test: accept output if given

- lib/groonga-query-log/command/run-regression-test.rb
- lib/groonga-query-log/command/verify-server.rb
- lib/groonga-query-log/filter-rewriter.rb
- lib/groonga-query-log/server-verifier.rb
- test/test-filter-rewriter.rb
This feature that for backward compatibility.
A new Groonga( version 5.0.7 or later) normalizes match target text by NormalizerAuto normalizer when Groonga doesn’t use an index for regular expression search.
Therefore, there is a possibility to a different result of regular expression search between an old Groonga and a new Groonga.
This feature replaces a complex regular expression that cannot use the index to doesn't use a regular expression.
> run-regression-test: support rewriting "column1 @ \"keyword\" && column2 @~ \"^(?!.*keyword1|keyword2|...).+$\""

- lib/groonga-query-log/statistic.rb
- test/test-parser.rb
When access to document root "/" is recorded, command is set to
nil. It causes the following error when calling command.arguments in
#to_hash method because to_hash doesn't care command==nil case.
NoMethodError: undefined method `arguments' for nil:NilClass
> Fix unexpected NoMethodError

- lib/groonga-query-log/command/run-regression-test.rb
- test/command/test-run-regression-test.rb
There is a case that groonga-query-log is invoked from shell script and it needs to report test result
as a use-case.
If groonga-query-log supports such notification feature by default, it makes more usable. (it also works easily on windows)
> run-regression-test: add notification support by E-Mail

- lib/groonga-query-log/command/run-regression-test.rb
- lib/groonga-query-log/command/verify-server.rb
- lib/groonga-query-log/filter-rewriter.rb
- lib/groonga-query-log/server-verifier.rb
- test/test-filter-rewriter.rb
This feature that for backward compatibility.
A new Groonga rewrite `&& !` to `&!` automatically for using index.
An old Groonga does not rewrite that.
Therefore, there is a possibility to a different result of calculating a score between an old Groonga and a new Groonga.
> run-regression-test: add a new rewrite filter for rewriting "&& !" operator

- lib/groonga-query-log/filter-rewriter.rb
- test/test-filter-rewriter.rb
We need a rewrite to false when reference is null.
Because new Groonga sets false if reference is null.
> Fix a rewrite value

- lib/groonga-query-log/command/run-regression-test.rb
- lib/groonga-query-log/command/verify-server.rb
- lib/groonga-query-log/performance-verifier.rb
- lib/groonga-query-log/server-verifier.rb
- test/test-performance-verifier.rb
In the previous versions, the value of median is used to check
performance regression, but there is a case that response time is a
bit slow in occasionally, in such a case, the value of median is not
proper.
> run-regression-test: use fastest elapsed time in comparison

- lib/groonga-query-log/command/format-regression-test-logs.rb
Because if the `response` is nil, `JSON.parse` is failed.
> format-regression-test-logs: add a nil check for response

- .github/workflows/test.yml
- groonga-query-log.gemspec
I got the following error in Ruby 3.1.
```
ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
```
```
/app/lib/groonga-query-log/command/run-regression-test.rb:24:in `require': cannot load such file -- net/smtp (LoadError)
from /app/lib/groonga-query-log/command/run-regression-test.rb:24:in `<top (required)>'
from bin/groonga-query-log-run-regression-test:20:in `require'
from bin/groonga-query-log-run-regression-test:20:in `<main>'
```
> Add `net-smtp` for Ruby 3.1 or higher

- test/test-replayer.rb
```
On subject Groonga::Client,
unexpected method invocation:
open(host: "127.0.0.1", port: 2929, protocol: :http, read_timeout: 60)
expected invocations:
- open({:host=>"127.0.0.1", :port=>2929, :protocol=>:http, :read_timeout=>60})
```
> test: Fix the passing of arguments

- lib/groonga-query-log/command/run-regression-test.rb
- lib/groonga-query-log/command/verify-server.rb
- lib/groonga-query-log/server-verifier.rb
Send `request_cancel` at random and test if it could be cancelled.
> Test for successful cancellation

- lib/groonga-query-log/command/check-crash.rb
They are useful to distinguish logs.
> check-crash: Show PID and thread ID

- lib/groonga-query-log/command/show-running-queries.rb
Running queries are started after base time and aren't finished at base time.
> show-running-queries: fix running query condition
